### ISSUE TITLE
Add precompiled Windows release - somewhere

### ISSUE THREAD

**Issue by bitbeans** [jedisct1/minisign#1]
It would be nice, if there is a precompiled Windows release (like in the dnscrypt-proxy 1.5).

So:
- a precompiled minisign.exe in the release package
- a seperate download/project site

**Comment by jedisct1** [comment]
Hi Christian,

Thanks for suggesting this!

Here is a start: https://jedisct1.github.io/minisign/

**Comment by bitbeans** [comment]
fast as always! :+1: 

thank you very much!
