### ISSUE TITLE
Support for post-quantum crypto

### ISSUE THREAD

**Issue by Timo67235** [jedisct1/minisign#102]
Given that minisign aims to be a modern crypto tool for the future, resiliance to future advances in quantum computing should be considered.

This could be implemented by offering an option to use hybrid signature algorithms that additionally uses post-quantum crypto for signatures.

At the moment the 3. round of the NIST Post-Quantum Cryptography Standardization has already resulted in a number of potential candidates for such algogithms https://en.wikipedia.org/wiki/Post-Quantum_Cryptography_Standardization

Will minisign receive support for post-quantum signature algorithms after the final NIST results have been published?

One of the noteable alternative candidates for minisign might be SPHINCS+ with key sizes of 32 Bytes for public and 64 Bytes for private keys (though signatures are 8 KB)

Support for post-quantum crypto will bring additional challenges such as large signatures or key sizes, however there might not be any alternative in the forseeable future, given that ED25519 will be broken as soon as quantum computers reach about 3000 qubits. Early support for hybrid signatures should therefore be considered.

**Comment by jedisct1** [comment]
The Minisign format can support multiple algorithms.

PQ signature systems can be added later on without breaking backwards compatibility.

But there's no rush. The PQC competition is not finished yet, it will still take years for something to be standardized based on its outcome, and signatures are less of a concern than key exchange. If a large quantum computer is built tomorrow, verifiers can be updated. This is not going to compromise past communications.

So, Minisign may eventually support some PQ scheme, but there's no need to jump the gun.

**Comment by Timo67235** [comment]
Thank you for the quick response!
Personally, I would like to see PQ support rather sooner then later, especially for use with long term signature keys.

Looking forward to PQ support in libsodium/minisign

**Comment by mibmo** [comment]
So.... is it time for ML-DSA?

**Comment by jedisct1** [comment]
No.

It's probably not going to be ML-DSA.
