### ISSUE TITLE
System trusted public keys

### ISSUE THREAD

**Issue by kallisti5** [jedisct1/minisign#103]
Is it possible to have a system directory of trusted public keys?

As a use case example, Haiku (the operating system) places read-only minisign public keys for our artifacts in ```/boot/system/data/trust_db``` (example: /boot/system/data/trust_db/haiku-2019.pub)

It would be a cool feature if minisign could additionally search this directory for system trusted signing keys.

Would minisign be interested in a patch doing something similar to this under Haiku?

**Comment by jedisct1** [comment]
As long as it doesn't add too much complexity to the code, why not!

Keys have identifiers, so I guess the plan would be to name files according to these identifiers?

**Comment by jedisct1** [comment]
Also, Haiku is nice, but such feature should ideally remain portable C that works on other operating systems as well.

**Comment by kallisti5** [comment]
Haiku's fully posix, so anything added would be portable :-)
