### ISSUE TITLE
"minisign: command not found"

### ISSUE THREAD

**Issue by Leonis87** [jedisct1/minisign#107]
Hi,
It is stated as dead simple tool for verifying signstures but I pull my hair for two days unable use this tool for verify Dnscrypt proxy on ubuntu 20.04.
I installed from Ubuntu Universe package and after installation try use it but ubuntu terminal spit out message:
"minisign: command not found"
I can compile it and install it from source but there is no releable information how to verify download (pgp).
What am I doing wrong ???

**Comment by jedisct1** [comment]
`minisign` doesn't seem to exist in Ubuntu 20.04

```sh
$ apt-cache search minisign
golang-github-jedisct1-go-minisign-dev - Minisign library for Golang
```

The only package they have is a development library for a programming language called Golang. Unless I missed something, there's no `minisign` tool available by default in Ubuntu.

You can compile the code from here, or use any of the other implementations such as [`minizign`](https://github.com/jedisct1/zig-minisign).

Maybe Ubuntu packages exist somewhere else, but I use a Mac so you know Linux better than I do :)

**Comment by Leonis87** [comment]
Yes that's true there isn't any minisign package in Ubuntu. I can compile from source but I don't know how to verify download from github. I can't find any PGP signature or key ...
