### ISSUE TITLE
minisig: No such file or directory

### ISSUE THREAD

**Issue by MrPaz** [jedisct1/minisign#112]
pardon my ignorance, what is going wrong here?  TIA

![minisign](https://user-images.githubusercontent.com/35268901/144769630-03311a88-1a1d-4666-b90d-e47dee8391d3.png)

**Comment by jedisct1** [comment]
The `barbet-factory-202112110.zip.minisig` file is missing. 

I don't know what "barbet factory" is, but in order to verify the signature, you need the file with the signature. It's probably available at the same place as you downloaded the zip file.

**Comment by MrPaz** [comment]
directions on CalyxOS site were slightly confusing to me, but this clarified the process and the signed file was indeed good.  thank you!
