### ISSUE TITLE
documentation: git commits 

### ISSUE THREAD

**Issue by nicolas-graves** [jedisct1/minisign#119]
Hi ! 
I was considering using minisign, but I find diffocult to find information about how to sign git commits with it. Git and Github documentation only take into account GnuPG.
Found these scripts https://codeberg.org/SkyFox42/git-minisign, but not sure using them would be the recommended way. 
Can you add a small documentation session on this and how to get git to work properly with minisign ? 
Thanks !

**Comment by nicolas-graves** [comment]
Closing the issue, not nterested anymore since I now use SSH to sign git commits.

**Comment by vimtoe** [comment]
> use SSH to sign git commits.

would you be kind enough to point me in the right direction please? @nicolas-graves  🙏

**Comment by nicolas-graves** [comment]
On 2023-11-26 00:15, vimtoe wrote:

>> use SSH to sign git commits.
>
> would you be kind enough to point me in the right direction please? @nicolas-graves  🙏 

There's a cool guide here : 
https://calebhearth.com/sign-git-with-ssh

There's however a small error in this guide, in some cases a "key::"
prefix is necessary, the git documentation is good too :
https://git-scm.com/docs/git-config#Documentation/git-config.txt-usersigningKey

-- 
Best regards,
Nicolas Graves
