### ISSUE TITLE
Better error message when passing wrong public key

### ISSUE THREAD

**Issue by rugk** [jedisct1/minisign#12]
When you pas the wrong public key (and e.g. accidentally use the signature) you get a base64 error.
```ShellSession
# minisign -Vm minisign -P fsadf
base64 conversion failed
```

I think this error message could be improved as the user does not know *what* failed to be converted and generally you do not really know what you did wrong here.

**Comment by jedisct1** [comment]
a205a35a1bdb6d8057ea1435d75bc95c299200af should improve this. Thanks!

**Comment by rugk** [comment]
Nice, but what about "valid" or "correct" rather than "actual"? Just an idea - I think this is more precious.

**Comment by jedisct1** [comment]
Because a signature that looks like a signature is not necessarily correct nor valid for the given message.
