### ISSUE TITLE
Use the same binary for GitHub releases and Docker images

### ISSUE THREAD

**Issue by bnoctis** [jedisct1/minisign#121]
I'm working on a [PR for thomasdesr/minisign-action](https://github.com/thomasdesr/minisign-action/pull/2), copying minisign binary from the `jedisct1/minisign` Docker hub image to save some run time.

However, the binary seems to be different from that in GitHub releases, thus can't be verified using the signature there. 

Specifically, 
```
8d591150c8b19fb888d95cf6271d2ece8e52196d /usr/local/bin/minisign
890eb1fadf9e2e61599e52277657dde648201bb9 minisign-0.10-linux/x86_64/minisign
```

**Comment by jedisct1** [comment]
Such container is generally expected to build stuff. Downloading the GitHub file may not be what people expect, especially since one is supposed to trust the entire Docker image.

I guess the best thing to do here would be to sign the image.

**Comment by jedisct1** [comment]
Done!

**Comment by bnoctis** [comment]
Yeah... signing the image is indeed better than a single binary. Thanks!
