### ISSUE TITLE
Add ppc64le support

### ISSUE THREAD

**Issue by mayurwaghmode** [jedisct1/minisign#123]
Tried executing minisign binary on ppc64le architecture but it failed with the below error
`./minisign: cannot execute binary file: Exec format error`

Commands followed

```
wget https://github.com/jedisct1/minisign/releases/download/0.10/minisign-0.10-linux.tar.gz
tar -xvf minisign-0.10-linux.tar.gz
cd minisign-0.10-linux/x86_64
./minisign
```

**Comment by jedisct1** [comment]
> `minisign-0.10-linux/x86_64`

This is compiled for x86_64. You mentioned that your CPU is a PPC64.
So, obviously, it is not going to work :)

You need to recompile it for your system.
