### ISSUE TITLE
Passing an empty string to -x is treated as if it was never set

### ISSUE THREAD

**Issue by MarcoFalke** [jedisct1/minisign#127]
Passing an empty string to `-x` will make it fall back to the default.

I am not entirely sure what to do here. For me, passing an empty string was by accident, so it was confusing to see a verified signature, and I'd prefer if the program failed. However, I can see how some users may see this as a "feature".

Another issue is that this behavior differs for rsign2:

```
$ minisign -Vm ./txt -x ""
Signature and comment signature verified
$ ~/.cargo/bin/rsign verify ./txt -x ""
could not read signature file : No such file or directory (os error 2)
```

Potential solutions:
* Clarify in the docs that an empty string is treated as if no option was supplied
* Change minisign or rsign2, so that they behave the same
* Something else? ...

**Comment by jedisct1** [comment]
There's only one specification for the format, and implementations must be compatible with each other.

Now, regarding command-line flags or additional features, implementations can do whatever they want.

Trying do emulate other implementations is a pain, and I'm not  sure it is worth it.

In the C implementation, `-C` changes the password, while in the Zig implementation, `-C` converts the key to an SSH key.

Is that an issue? I don't think it is. Pick one implementation and stick to it :) For a given tool, not having a command-line flag suddenly work differently seems preferable.
