### ISSUE TITLE
Pre-built Linux binaries?

### ISSUE THREAD

**Issue by rugk** [jedisct1/minisign#13]
What about pre-built Linux binaries?

I think it would be nice if they are offered too.

**Comment by jedisct1** [comment]
Providing binaries for Linux is tricky. There are way too many distributions, way too many architectures, and way too many package formats.

People want official packages made and supported by package maintainers that know the distributions they use, not suspicious binaries that haven't been tested at all on their platform.

minisign is already part of all BSD systems and has official packages in some Linux distributions. If it's not available for the distribution you use, maybe you can help, by building packages, contacting potential package maintainers, proposing it on related mailing lists, etc.

**Comment by rugk** [comment]
Thanks for the information. This was more a theoretical question.

What about listing all distributions where someone already made a package? This way users know what package are available and can simply install it.

**Comment by jedisct1** [comment]
Same thing... It's next to impossible to track what's going on in all free operating systems and distributions. Don't expect vendors, commercial or not, to let software authors know about what they do with their software either; it never happens.

**Comment by FranklinYu** [comment]
Late to the party, but there is a third-party website called Repology. It provides a page like https://repology.org/project/minisign and a (long) badge like

[![Packaging status](https://repology.org/badge/vertical-allrepos/minisign.svg)](https://repology.org/project/minisign/versions)
