### ISSUE TITLE
how to verify the minisign download itself

### ISSUE THREAD

**Issue by shishini** [jedisct1/minisign#130]
i want to use minisign to verify a download
but how can i verify the minisign download itself 

can you add SHA hashes?

**Comment by jedisct1** [comment]
Anybody can compute a SHA hash. It doesn't include a secret key, this is not a signature.

The minisign archives themselves are signed with minisign. So you can use any other version to verify them, including [other implementations](https://github.com/jedisct1/minisign#additional-tools-libraries-and-implementations).

My public key is available in multiple places. Such as the Minisign documentation, the libsodium documentation, [here](https://download.libsodium.org), or [here](https://github.com/jedisct1.keys).

**Comment by shishini** [comment]
well a SHA hash is not a signature, but it provide a way to verify a download and provide an additional level security, its common for many projects to provide it 

anyway, thanks for the reply 👍
