### ISSUE TITLE
namespace in public key

### ISSUE THREAD

**Issue by badiku** [jedisct1/minisign#134]
hi, as doc says that a public key has 3 parts: Ed and random 8 bytes key_id and edpub,

I wan to know what the 8bytes random key_id is used for.

what if I set key_id to all zero, [00000000](tel:00000000), or some fixed string?

does all zero reduce security of the key?

can I use these 8 bytes for other usage, for example, to make a namespace.  like root, root/ca, root/ca/1 , to include some identity info in random generated key?

if multi minisign keys use one same Ed25519 pair, only the key_id is different, is this ok?

e.g.  my minisign public key is :
```
RWS+github/badiku+0001abcdabcd...

RWS+github/badiku+0002abcdabcd...
```

**Comment by badiku** [comment]
hi,
as said,minisign immediately reports when key_id mismatch:
>minisign.exe -Vm a.txt -P RWSs00nq/a5oV8bsYOTEPO7SnE8u/L6OAQ6qO6/PZVW5rCPoHbOA9f+q
>Signature key id in a.txt.minisig is 5768AEFDEA49DFAC
>but the key id in the public key is 5768AEFDEA49D3AC

my thought is that , this reported key_id is in HEX form, and the public key provided is usually in base64.  

and HEX is not that user friendly, one cannot easily encode HEX to base64.
and actually the b64decoded HEX is reversed like this: 4564acdf49eafdae6857...

how about report in base64, "signed by public key RWSabcdef....."

this way if the prefix of public key is some user defined string, 
then it gets printed and is more meaningful than technical HEX random bytes, like this:
```
this signagure need a publik key starts with RW+github/myname+abcd001....
```

**Comment by jedisct1** [comment]
The actual key ID in hex is printed right before the base64 blurb:

> untrusted comment: minisign public key 3B1EAD3311E2FEFC

The base64 blurb is far less readable and the first bytes are not part of the key ID. Other implementations also support other formats for the public key, for example the Zig implementation allows it to be in SSH format.

**Comment by badiku** [comment]
> The base64 blurb is far less readable

well, I do not think so. maybe only programmers think that HEX string is more readable.

compare this:
```
the signature need keyid 5768AEFDEA49DFAC
the signature need keyid 5768AE4DEA49DFAC
the signature need a public key starts with RWS/badiku/1
the signature need a public key starts with RWS/badiku/2
the signature need a public key starts with RWS/badiku/3
```

I think custom base64 string is far more readable than random HEX id.

but it is ok that we do not agree with each other. I can use my own compiled version.
