### ISSUE TITLE
Default minisign keys location (e.g. ~/.minisign)

### ISSUE THREAD

**Issue by grempe** [jedisct1/minisign#14]
Experimenting with `minisign` I was a bit surprised to see that the keys generated are just dropped in the current dir.  This also implies that the default usage of minisign would require the private key to be sitting in the same directory you are running minisign from and would need to be moved around or always specified with `-s <seckey>`.

While there is nothing really inherently wrong with this, it would be much more convenient if a default location, in addition to the current dir, was checked for keys.  I would propose that minisign should, by default, create (with perms 700) and drop its keys in the ~/.minisign dir.  If keys already exist it should warn and exit so as not to overwrite. minisign should complain and exit if the dir is not 0700 for security.

When running minisign to sign, or verify, it should look in that as a secondary default location (in addition to current dir) for keys.

You could kind of simulate this behavior today by storing the key files in any arbitrary dir and always passing in that path with the `-s <seckey>` option but this is kind of a pain to remember to do every time. You can't really fix it with an alias either since sometimes you need to pass in the secret key path, and sometimes the public key path, but not always both.

If you want to take this one step further. Have a ~/.minisignrc file (optional) that would allow the user a way to specify the default path where keys should be looked for instead of current dir or ~/.minisign.  This would be useful if, for example, the keys lived on an external usb flash drive which is only connected when needed but would *always* mount to a known location.

Thanks!

**Comment by jedisct1** [comment]
That's a good suggestion, thanks!

Definitely something I will add to the next release.

**Comment by JayBrown** [comment]
I second that. An rc file would be _very_ nice.

**Comment by jedisct1** [comment]
Done!

**Comment by grempe** [comment]
Thanks Frank, I was glad to see this request come to life.

I have a couple of nitpicks maybe you can comment on or address.

- I already had a ~/.minisign dir (which I created at the time I filed this feature request just for my own convenience to have a place to store those files).  When I compiled and generated a new test keypair just to see what would happen this evening I noted that you blindly overwrote the `minisign.key` file I already had installed there (a real one, don't worry I keep a backup in 1password :-).  I would suggest you test to see if a file already exists in that dir and prompt the user to either confirm, abort, or store the file in the local dir.  **Obviously this has key data loss possibilities**.

- When you generate a new keypair, you store the `minisign.key` in the new default dir (`~/.minisign`) which is great!  However, you don't do the same for the `minisign.pub`.  Why not stick them both in there at creation time and also look for it there if the user is verifying a file and no `minisign.pub` file is in the local dir, use that one as the fallback.  I suppose this would be used in the scenario where someone is verifying a file that they themselves signed as opposed to downloading a file, its signature, and someone's public key to verify. Even if you don't lookup the public key automatically it would be useful I think to just store the keys together in that dir at creation time so you always know where to find both.

Cheers,

Glenn

**Comment by grempe** [comment]
Related:

https://github.com/jedisct1/minisign/issues/8

**Comment by grempe** [comment]
Also note, I just took a look at the homebrew installation formula for minisign:

https://github.com/Homebrew/homebrew-core/blob/fb81645562f7e495a49561065912788af2d1f14f/Formula/minisign.rb#L29

And it appears to run `minisign -G` as parts of its test run on installation.  I think this is going to silently overwrite the users real private key in ~/.minisign with fake test keys when they just install an upgraded minisign (actually probably after a second release is updated in homebrew). No?

**Comment by JayBrown** [comment]
One lcomment: putting the .pub key files in `~/.minisign` would not be such a super idea, because users may want to share their .pub key files, not only their keys. As part of my scripts I'm copying (and looking for) the .pub keys in `~/Documents/minisign`. Maybe this directory (or another fixed _visible_ directory) should be the standard dir for the .pub key files. For the private key files I'm currently using `~/Documents/minisign/prvt` with `chflags hidden`, but will change that to `~/.minisign` once the new update is there.
