### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by CryptDNS** [jedisct1/minisign#143]
I have a problem in This error appears when Creating a key pair
version 0.11 
windows 7 ultimate 64
![Capture](https://github.com/jedisct1/minisign/assets/162744892/850b6670-310c-49dd-b08e-9d27c7e710c8)
> Problem signature:
> Problem Event Name:	APPCRASH
> Application Name:	minisign.exe
> Application Version:	0.0.0.0
> Application Timestamp:	63c8504d
> Fault Module Name:	minisign.exe
> Fault Module Version:	0.0.0.0
> Fault Module Timestamp:	63c8504d
> Exception Code:	c000001d
> Exception Offset:	000000000001db47
> OS Version:	6.1.7601.2.1.0.256.1
> Locale ID:	1033
> Additional Information 1:	c871
> Additional Information 2:	c8711acb55532bef167eaa191d5a71be
> Additional Information 3:	e926
> Additional Information 4:	e9262df05bed1ca736b85e561ae14604
> 
> Read our privacy statement online:
> http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409
> 
> If the online privacy statement is not available, please read our privacy statement offline:
> C:\Windows\system32\en-US\erofflps.txt

**Comment by jedisct1** [comment]
What CPU do you have? Maybe your CPU is too old for the precompiled version.

**Comment by jedisct1** [comment]
I updated new Windows binaries that *may* work on older systems and CPUs. But keep in mind that Windows 7 reached end of life in 2020. Microsoft doesn't support it any more, neither do recent compilers.
