### ISSUE TITLE
Windows binaries for version 0.11 have been updated?

### ISSUE THREAD

**Issue by Skycoder42** [jedisct1/minisign#144]
Hi :)

I saw that the windows binaries have been updated 5 days ago. However, there are no changes in the code. I was wondering why they have been updated and just wanted to make sure nothing fishy is going on, as attacks on GitHub repositories have been on the rise lately and this is a security critical application.

**Comment by Ra2-IFV** [comment]
Agree, I'm using scoop too, the error is quite annoying.  
@jedisct1 Can you update artifact names?

**Comment by jedisct1** [comment]
Done!

**Comment by Ra2-IFV** [comment]
Thanks! It's a nice project, keep it up!
