### ISSUE TITLE
Does .pub file really need a comment?

### ISSUE THREAD

**Issue by MarcinKonowalczyk** [jedisct1/minisign#147]
I was recently downloading zig 0.14.0-dev and wanted to verify the signature. Before I realised there is the `-P` flag for direct pub key input, i've done `echo <pub-key> > zig.pub` and then `minisign -V -p zig.pub -m ...` to then be told that there was an `Error while loading the public key file`.

Looking at the code, it looks to me like `pk_comment` in `pubkey_load_file` is not really doing much. Maybe worth changing `pubkey_load_file` to something like this:

```c
#define MAX_LINES_TO_READ_FROM_PUB_FILE 128

int is_comment_line(const char *line) {
    // Check if 'line' starts with a comment prefix
    return strncmp(line, COMMENT_PREFIX, strlen(COMMENT_PREFIX)) == 0 ||
           strncmp(line, TRUSTED_COMMENT_PREFIX, strlen(TRUSTED_COMMENT_PREFIX)) == 0;
}

for (int i = 0; i < MAX_LINES_TO_READ_FROM_PUB_FILE; i++) {
    char line[COMMENTMAXBYTES];
    if (fgets(line, (int) sizeof line, fp) == NULL) {
        exit_msg("Error while loading the public key file");
    }

    if (is_comment_line(line)) {
        continue;
    }

    // Not a comment line, therefore a key line
    // ....
}
```

I guess it's to read filed generated with `-G`, but since the comment is untrusted, i wonder whether it matters here.

**Comment by jedisct1** [comment]
Hi!

The comment in the public key is required for compatibility with another tool called `signify`, used in OpenBSD.

It's also useful if you have multiple public keys, and don't remember which one is the correct one for a given signature : when given the wrong one, the tool will tell you what the expected signature ID is.

**Comment by jedisct1** [comment]
The comment is not strictly necessary. But as multiple implementations exist, it would not be great if this particular implementation suddenly started to accept keys without it, while the same key file would fail with other implementations.

public key files are meant to be downloaded directly, not copy/pasted. If a web server displays them as text instead of triggering a download, it's a configuration issue.

**Comment by MarcinKonowalczyk** [comment]
Cool. Gochya 👍 The only thing I'd then suggest is to maybe change the error message to something like: `Error while loading the public key file. The first line of the key file should be an (untrusted) comment.`.

**Comment by MarcinKonowalczyk** [comment]
Oh, and re pub keys being copy/pasted, I was just using what i could find on the [zig downloads page](https://ziglang.org/download/).

**Comment by MarcinKonowalczyk** [comment]
Closing the issue btw. Ty for a fast reply and a cool project! 😊
