### ISSUE TITLE
Trying to sign a zero-byte file results in 'Undefined error: 0'

### ISSUE THREAD

**Issue by grempe** [jedisct1/minisign#15]
I was doing some testing and had created a zero byte file foo.txt.  Trying to sign this (using various permutations) was failing for me with `Undefined error: 0`.  I determined that this happens if the file you are trying to sign is empty. If you put anything in the file it signs normally.

While it may not make sense normally to sign a zero-byte file it should handle this more gracefully and with a meaningful error message.

````
/tmp/test$ ls -la
total 0
drwxr-xr-x  3 glenn 102 Dec 29 23:12 .
drwxrwxrwt 18 root  612 Dec 29 23:04 ..
-rw-r--r--  1 glenn   0 Dec 29 23:12 foo.txt

/tmp/test$ minisign -Sm foo.txt -s ~/.minisign/minisign.key
Password:
Deriving a key from the password and decrypting the secret key... done

foo.txt: Undefined error: 0
````

**Comment by jedisct1** [comment]
e748f644dd443d84e702fcdf766c4d9d5fe5cb19 should fix it.

Thanks!
