### ISSUE TITLE
Unadulterated versions of the private, public and signature values.

### ISSUE THREAD

**Issue by xylesoft** [jedisct1/minisign#18]
Currently the binary will create the minisign.key, minisign.pub and <file>.minisig file in a customised format, generally containing prefixed byte data, in my situation I need the raw values without the other information.

So my suggestion is It might be a good idea to provide a option which allows you produce the pure key/sign values for use with testing other implementations of ed25519 which do not rely on the hash identify or the 8bytes etc. 

Thanks,

**Comment by jedisct1** [comment]
That would be a completely different and incompatible tool.
Minisign is not even dedicated to using Ed25519, this can change later. So you can't really use it as a command-line tool to compute an Ed25519 signature.
