### ISSUE TITLE
Windows build lacking some options

### ISSUE THREAD

**Issue by Nurple** [jedisct1/minisign#2]
Heya, it seems the windows build isn't v0.3, as it lacks -v and -P, same goes for the bundled copy with dnscrypt as it's the same file.

**Comment by jedisct1** [comment]
Indeed :( I was lazy and just took the binary from dnscrypt-proxy, without realizing that changes had been made between this and the 0.3 release.

This has been fixed; the Windows binary has been updated. Thanks!
