### ISSUE TITLE
How to install minisign-0.6.tar.gz.minisig?

### ISSUE THREAD

**Issue by cokeflash** [jedisct1/minisign#20]
How to install minisign-0.6.tar.gz.minisig?
I can't extract the file :/

Please help, thanks!

**Comment by jedisct1** [comment]
`minisign-0.6.tar.gz.minisig` is the signature for `minisign-0.6.tar.gz`.

So, you don't install this; it's just a text file.

Install `minisign-0.6.tar.gz` instead (or get a precompiled binary) instead.

**Comment by cokeflash** [comment]
Where I get the tar.gz file of minisign?

**Comment by jedisct1** [comment]
What operating system are you using?

**Comment by cokeflash** [comment]
Ubuntu 15.10 Wily

**Comment by jedisct1** [comment]
Click "Download source code" at the top of the web page https://jedisct1.github.io/minisign/

**Comment by cokeflash** [comment]
Thanks, but how can I install the source of minisign? cmake.. make etc. won't work.

**Comment by cokeflash** [comment]
when I start "DNScrypt-Loader" then I got this error-message:  Sorry Minisgn was not found.                   │               
               │ Please check if the program was installed.

**Comment by cokeflash** [comment]
Installed ;-)

**Comment by jedisct1** [comment]
Congrats!
