### ISSUE TITLE
Info: minisign shell scripts/workflows

### ISSUE THREAD

**Issue by JayBrown** [jedisct1/minisign#21]
fyi: I have uploaded the first version of a script/workflow to verify files with minisign. `minisign-sign` will be added at a later date. (Edit: has been added now.)

https://github.com/JayBrown/minisign-misc

**Comment by jedisct1** [comment]
Well done, Jay! This is really neat!

**Comment by JayBrown** [comment]
Now at v1.7… quite an overhaul. Verifying is now a lot slimmer, while signing has more options/capabilities.

**Comment by jedisct1** [comment]
Congrats! This release looks amazing. I was just trying it as we speak.

I made a typo when entering the password, so signing doesn't work until the password is manually removed from the keychain. Maybe you should provide instructions about how to do this :)

**Comment by JayBrown** [comment]
Just tested it, and yes, that's not a good thing. Maybe I should add another option in the signing list plus a routine to update the password of a secret key.

(fyi: I accidentally uploaded an intermediate version from last night to github… it was only up for 2 or 3 minutes, but maybe you didn't download the actual v1.7 from tonight.)

**Comment by JayBrown** [comment]
v1.7.1 with password-update option

**Comment by jedisct1** [comment]
Wow :)

**Comment by jedisct1** [comment]
Thanks for doing this! Closing this issue, as a link to your tools was added to the documentation quite some time ago.
Thanks!
