### ISSUE TITLE
Question: public key format

### ISSUE THREAD

**Issue by JayBrown** [jedisct1/minisign#23]
I'm trying to enhance my minisign-verify workflow by checking the clipboard contents first. So my question is, if the public keys (a) are always 56 characters long, (b) only have "+" and "/" as special characters, and (c) are otherwise made up of A–Z, a–z, and 0-9.

The function I'm currently thinking about for checking the public key is like this:
```
pkch () {
	case $1 in
		( *[!0-9A-Za-z+/]* | "" ) echo "false" ;;
		( * )
			case ${#1} in
				( 56 ) echo "true" ;;
				( * ) echo "false" ;;
			esac
	esac
}
```

EDIT: additional question… public keys always seem to begin with "RW", correct? The function would then be:
```
pkch () {
	case $1 in
		[!RW]* ) echo "false" ;;
		* )
		case $1 in
			( *[!0-9A-Za-z+/]* | "" ) echo "false" ;;
			( * )
				case ${#1} in
					( 56 ) echo "true" ;;
					( * ) echo "false" ;;
				esac
		esac
	esac
}
```

**Comment by jedisct1** [comment]
Hi Jay,

Yes, that's absolutely correct. The size is constant, and the key is base64-encoded, so it will always match your regex.

And yes, it will always start with `RW` :)

**Comment by JayBrown** [comment]
Thank you. Will upload the new updates soon hopefully.
