### ISSUE TITLE
Error: base64 conversion failed

### ISSUE THREAD

**Issue by the-bobo** [jedisct1/minisign#24]
Can't seem to get the command line syntax quite right. Trying to manually verify the latest dnscrypt-resolvers.csv. 

I downloaded dnscrypt-resolvers.csv, dnscrypt-resolvers.csv.minisig, and minisign.pub into a folder. Trying the following commands do not work:
`minisign -Vm dnscrypt-resolvers.csv -x dnscrypt-resolvers.csv.minisig    `
`base64 conversion failed  `

`minisign -Vm dnscrypt-resolvers.csv -p minisign.pub   `
`base64 conversion failed  `

`minisign -V -P "RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3" -m dnscrypt-resolvers.csv  `
`Untrusted signature comment should start with "untrusted comment: "`

  
I've read the documentation several times but am not sure what I'm doing wrong. Help appreciated, thanks!

**Comment by jedisct1** [comment]
```bash
minisign -Vm dnscrypt-resolvers.csv -p minisign.pub
```
and
```bash
minisign -Vm dnscrypt-resolvers.csv -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3
```
should both work.

Looks like the files you downloaded are corrupted.

**Comment by the-bobo** [comment]
Issue resolved - I needed to save from the RAW links, was accidentally getting the HTML files. Once I got the RAW files I could validate successfully with 
`minisign -Vm dnscrypt-resolvers.csv -p minisign.pub`

I could then replace the contents of `/Library/PreferencePanes/DNSCrypt.prefPane/Contents/Resources/usr/share/dnscrypt-proxy` with the new
```
dnscrypt-resolvers.csv		minisign.pub
dnscrypt-resolvers.csv.minisig
```
and my DNSCrypt resolvers successfully update, thanks.
