### ISSUE TITLE
Sign commits & releases (tags)

### ISSUE THREAD

**Issue by rugk** [jedisct1/minisign#26]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/generating-a-gpg-key/
* And here is how you can sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases

**Comment by jedisct1** [comment]
That's painful and discouraging from writing new code. Especially since GPGtools don't work on Sierra yet.

**Comment by franklouwers** [comment]
maybe you could minisign new releases? <g>

**Comment by jedisct1** [comment]
Of course releases have always been signed with minisign :) 
https://github.com/jedisct1/minisign/releases
