### ISSUE TITLE
minisign-0.7-2 doesn't compile in Ubuntu 16.10

### ISSUE THREAD

**Issue by cmschroeder91** [jedisct1/minisign#27]
The CMake script executes with OK, but the make fails in Ubuntu 16.10. I'm guessing there is a version dependency problem. Ubuntu 16.10 provides gcc 6.2.0 and libsodium18 and its associated dev pkg (Ubuntu version 1.0.11-1). Attached is the log from the make.
[build_log.txt](https://github.com/jedisct1/minisign/files/679848/build_log.txt)

**Comment by jedisct1** [comment]
Did you install `libsodium-dev`?

**Comment by jedisct1** [comment]
I'm awfully sorry, but I wasn't able to reproduce this, using the normal 0.7 source code tarball on a new Ubuntu 16.10 install.

The only packages I installed were `build-essential`, `libsodium-dev` and `cmake`.

So, I don't know what is different on your system. Maybe the `libsodium-dev` package was not installed.

**Comment by cmschroeder91** [comment]
No, libsodium-dev is installed; I checked the version while writing my initial post. I downloaded the 'jedisct1-minisign-0.7-2-g4dcfeb8.tar.gz' tarball using the link https://github.com/jedisct1/minisign/tarball/master from the 'Download source code' button on the https://jedisct1.github.io/minisign/ web page. I noticed the last release on github was 0.7, so I will try it instead.

**Comment by cmschroeder91** [comment]
I downloaded minisign-0.7.tar.gz, verified I had the packages you mentioned installed (I did), but it still doesn't build on my system (see attached log).
[build_0.7_log.txt](https://github.com/jedisct1/minisign/files/679888/build_0.7_log.txt)

**Comment by jedisct1** [comment]
Check that you don't have multiple versions of libsodium installed, maybe one in `/usr` and another one in `/usr/local`.

**Comment by cmschroeder91** [comment]
Ah, I do have libsodium10 in /usr/local/lib from 2014 when I built dnscrypt from source for a previous Ubuntu distro. Can I tweak CMake to pick up the correct version needed by minisign (I'm still rather new to CMake)?

**Comment by jedisct1** [comment]
You really should just remove that old junk from 2014 :)

**Comment by cmschroeder91** [comment]
It's more complicated. I have multiple Ubuntu distros installed and typically share /usr/local between them. I will need to rejigger to move libsodium10 out of /usr/local to be truly local to the distro that uses it. I know that CMake rules can define the minimum version required for a dependent lib and thought that would be a better/quicker solution.

**Comment by cmschroeder91** [comment]
OK, I moved the old libsodium10 out of /usr/local and minisign 0.7 built successfully. Do you know what the libsodium minimum required version is?

**Comment by jedisct1** [comment]
Version >= 1.0.0 are probably fine.

**Comment by cmschroeder91** [comment]
For the record, successfully built using libsodium18 (1.0.11-1) and build failed using libsodium10 (0.5.0?).

**Comment by jedisct1** [comment]
0.5.0 is so old that you really can't expect it to be compatible. The API wasn't even stable back then.
