### ISSUE TITLE
fail to verify dnscrypt sources signature

### ISSUE THREAD

**Issue by ssten** [jedisct1/minisign#28]
To verify dnscrypt sources I've installed git version (today's build) of minisign.

Trying to execute command, recommended on https://github.com/jedisct1/dnscrypt-proxy/ failed with the following error message:

> $ minisign -VP RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3 -m dnscrypt-proxy-1.9.4.tar.bz2 
> dnscrypt-proxy-1.9.4.tar.bz2.minisig: No such file or directory

**Comment by jedisct1** [comment]
Hi ssten,

You need to download the `dnscrypt-proxy-1.9.4.tar.bz2.minisig` file, which contains the signature.

Signature files are available from the same location as the source files.

**Comment by jedisct1** [comment]
If this wasn't clear enough, this is probably something worth mentioning in the wiki. I'll try to improve that as soon as possible.

**Comment by ssten** [comment]
I've guessed, that I need to fetch signature file. But later.

Probably not only wiki, but improve error message in minisign, adding string like «missed signature file».

**Comment by sancao2** [comment]
```
~ minisign -V -x dnscrypt-proxy-macos-2.0.19.tar.gz.minisig -m dnscrypt-proxy-macos-2.0.19.tar.gz                                                                                                                        19:38:30
minisign.pub: No such file or directory
```
I got a similar warning sentence too.

**Comment by sancao2** [comment]
```
~ minisign -v                                                                                                                                                                                                           
minisign 0.8
```
in mac platform
