### ISSUE TITLE
minisig for newest tarballs missing

### ISSUE THREAD

**Issue by Strayer** [jedisct1/minisign#33]
I'm writing a Dockerfile that installs dnscrypt and I thought it would be nice to install minisig beforehand to verify the signatures of minisig itself and dnscrypt.

To be sure minisig hasn't been tampered with I thought about including the .minisig of the source tarball, but neither 0.6 nor 0.7 seem to have a minisig in the releases tab.

**Comment by jedisct1** [comment]
You mean the archives automatically generated by Github?

I didn't think about downloading these to add a signature, but why not! These files are not going to change after a tag has been added, so signatures can be safely added.

**Comment by jedisct1** [comment]
Added for version 0.7!
