### ISSUE TITLE
Windows binaries 0.8

### ISSUE THREAD

**Issue by bitbeans** [jedisct1/minisign#37]
Am I too impatient or have the win32 binaries been forgotten? :)

**Comment by jedisct1** [comment]
Not forgotten. Since I don't have a Windows machine, it always takes more time for me to build Windows binaries.

**Comment by bitbeans** [comment]
okay, accepted :)

**Comment by jedisct1** [comment]
dnscrypt-proxy binaries are automatically generated by Travis, which is boring and unauthentic.

libsodium and minisign binaries are hand-crafted with love.
