### ISSUE TITLE
Minisign as a library?

### ISSUE THREAD

**Issue by jaddr2line** [jedisct1/minisign#40]
Currently my package manager uses minisign in order to verify signatures on package metadata. In a future version, I would like to be able to download these into memory and verify without extra I/O. If this is too complicated, I can try using pipes instead (although this would be less efficient).

**Comment by jedisct1** [comment]
I wrote a minisign verify library, but in Go: https://github.com/jedisct1/go-minisign

The current C code shouldn't be difficult to split into a command-line part and a generic library, but this is not something I'll have time to work on in a near future.

**Comment by jadr2ddude** [comment]
Ok. I can try to split it into a library and send a pull if i make any progress

**Comment by jedisct1** [comment]
Why add yet another build system?

**Comment by jadr2ddude** [comment]
So an update: my project depending on minisign is pretty much dead right now. However, if there is still interest in this, I can try to do this anyways.
