### ISSUE TITLE
Argument option for no password and password passing

### ISSUE THREAD

**Issue by udf2457** [jedisct1/minisign#43]
Hi,

For the purposes of scripting, it would nice to have two extra argument options:

1. The ability to define a key with no password (for testing and/or non security-critical applications)

2. The ability to pass a key via command line or reference to a file or somesuch.

**Comment by jadr2ddude** [comment]
For now you can do ```echo | minisign something``` to use an empty password. This is a workaround I have used.

**Comment by jedisct1** [comment]
Yes, absolutely. And for a non-empty password, put in into a temporary file and use `minisign ... < file`.
