### ISSUE TITLE
Q: Can I create minisign readable signatures with keys not created by minisign?

### ISSUE THREAD

**Issue by enko** [jedisct1/minisign#44]
[Scuttlebutt](https://www.scuttlebutt.nz/) is a decentral message passing network (which also can and is used as a social network) that uses ed25519 keys as the core identifier of an identity. There was [an idea](https://viewer.scuttlebot.io/%252j6N3z2eL3C15w16SGjdXe/PMkAgp2XI2wV4Tp6L+HY=.sha256) to create signatures with this ed25519 key for the binaries of scuttlebutt clients. Can I pass my secret key which was created by scuttlebutt somehow to minisign? From reading the docs and the secret key format this seems rather complicated, because of all the key derivation stuff.

Thanks for your time and your great work with libsodium!

**Comment by jedisct1** [comment]
You can, but that key will still need to be encrypted with a stream derived from a password. Which can be empty, though.
