### ISSUE TITLE
Verifying minisign download - how do I 

### ISSUE THREAD

**Issue by taoje** [jedisct1/minisign#45]
Could you let me know how I verify minisign before installing? I saw that earlier versions came with a .minisig file but that would mean installing minisign to check its minisig. 

I could not find the .minisig for the latest version of minisign.

But I have noted that the libsodium tar comes with a .sig which can be verified outside minisign with gpg. 

Could you let me know how to verify the minisign download I have as authentic; other than it comes from the 'right' HTTPS site?

**Comment by jedisct1** [comment]
A `TXT` DNS query for `<filename>.hash.dnscrypt.info` returns the SHA256 hash of that file:

```
$ dig txt minisign-osx.zip.hash.dnscrypt.info
minisign-osx.zip.hash.dnscrypt.info. 3600 IN TXT "028720d3406b958ffa272018335e4eabf0f19a87462d86b6be248b3bb16dd4ca"
```

**Comment by jedisct1** [comment]
Your operating system probably also comes with packages for it.

On Windows, you can install it with Chocolatey, on MacOS with Homebrew. So you don't need to download it from here.

**Comment by jedisct1** [comment]
> This seems to no longer be possible?

That was 7 years ago.

**Comment by ernstki** [comment]
> > This seems to no longer be possible?
> 
> That was 7 years ago.

There's still a chicken-and-egg problem for users of older LTS distros which [do not yet have a `minisign` package](https://packages.ubuntu.com/search?keywords=minisign&searchon=names&suite=jammy&section=all): one can't verify the Zig download to build minisign without minisign.

@jedisct1 Perhaps manually uploading checksums computed on your end to the release notes for [0.12](https://github.com/jedisct1/minisign/releases/tag/0.12) is a good compromise?

I believe if you were to do a new release _now_, SHA256 checksums for the assets will be added to the release page automatically, as seen [here](https://github.com/orgs/community/discussions/23512#discussioncomment-13339927). This appears to have been enabled [in June 2025](https://github.blog/changelog/2025-06-03-releases-now-expose-digests-for-release-assets/).
