### ISSUE TITLE
Possibly buffer too short by one?

### ISSUE THREAD

**Issue by emmenlau** [jedisct1/minisign#48]
Is it possible that the char buffer in https://github.com/jedisct1/minisign/blob/master/src/base64.c#L77 is too short by one character? If I compile the code as C++ in `-pedantic` mode, gcc complains that the initializer string is too long. I would guess the compiler adds a zero-terminator at the end? However I'm not an expert for C, maybe there its different?

Please ignore my humble comment if C behaves different than C++ in this aspect.

**Comment by jedisct1** [comment]
This is correct in C, and is the standard way to not include a trailing `\0`.

C++ is different because strings has different representations; `std::string` objects are not terminated while C-like strings are.

But Minisign is written in C, not C++.
