### ISSUE TITLE
Compiled executable failed to find target

### ISSUE THREAD

**Issue by sudormrfstar** [jedisct1/minisign#49]
I am trying to run my minisign the first time, but it failed with error: "kore-3.2.2.tar.gz.minisig: No such file or directory" from the following command:

$./minisign -Vm kore-3.2.2.tar.gz -P RWSxkEDc2y+whfKTmvhqs/YaFmEwblmvar7l6RXMjnu6o9tZW3LC0Hc9
kore-3.2.2.tar.gz.minisig: No such file or directory

$ echo $?
2
information about my environment:

$cat /proc/version
Linux version 4.18.16-300.fc29.x86_64 (mockbuild@bkernel04.phx2.fedoraproject.org) (gcc version 8.2.1 20180801 (Red Hat 8.2.1-2) (GCC)) #1 SMP Sat Oct 20 23:24:08 UTC 2018 

here is how I compiled minisign, which was downloaded from https://jedisct1.github.io/minisign/, note that I did NOT install it; I was running it from my ./build directory directly.
    $ tar zxf jedisct1-minisign-0.8-3-g9eac49b.tar.gz

    $ # ...
    $ mkdir build
    $ cd build
    $ cmake ..

    $ make -j2

**Comment by jedisct1** [comment]
Do you have the `kore-3.2.2.tar.gz.minisig` file that contains the signature?
