### ISSUE TITLE
Feature request: simple trusted-comment-only clearsign mode

### ISSUE THREAD

**Issue by vi** [jedisct1/minisign#50]
Something like

    minisign -S -t 'This short-message is protected.' -m /dev/null -x output.clearsig

, but without the `untrusted comment: signature from minisign secret key\nRW...s=\n` part at all, and without a file to verify.

This should produce short QR-code-able unforgeable messages, like gpg's `--clearsign`.

**Comment by jedisct1** [comment]
Comments are only a single line, so that would be a very rare use case, in addition to being a breaking format change.

So, I'd rather not do that.
