### ISSUE TITLE
Feature request: print pubkey based on privkey

### ISSUE THREAD

**Issue by vi** [jedisct1/minisign#51]
Like WireGuard's `wg pubkey`.

**Comment by jedisct1** [comment]
I don't use Wireguard. What does it do?

**Comment by vi** [comment]
WireGuard is a VPN solution which also uses ed25519 keys, as far as I understand.

The point that it has a command to print the public key given a private key. I expect it to be easy and obvious operation.

Just getting `minisign.pub` from `minisign.key`.

**Comment by jedisct1** [comment]
> getting `minisign.pub` from `minisign.key`.

Done!
