### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by brunowego** [jedisct1/minisign#53]
Hi @jedisct1, can I submit a PR for provide docker support?

```sh
cat << 'EOF' | docker build -t minisign:0.8 -
FROM alpine:3.9 as build

WORKDIR /usr/src/minisign

RUN apk add --no-cache cmake make g++ libsodium-dev

RUN wget -O - https://github.com/jedisct1/minisign/archive/0.8.tar.gz | tar -xz --strip-components 1 && \
    mkdir build && cd build && \
    cmake .. && \
    make && make install


FROM alpine:3.9

RUN apk add --no-cache libsodium-dev

COPY --from=build /usr/local/bin/minisign /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/minisign"]

EOF
```

Running:

```sh
docker run -it --rm minisign:0.8 -h
```

**Comment by brunowego** [comment]
If yes, can you register https://hub.docker.com/u/minisign?

**Comment by jedisct1** [comment]
Why not, but having an Alpine Linux distro would be a little bit overkill to run just a simple, small binary that can be statically linked.

The `scratch` image would be sufficient :)

**Comment by brunowego** [comment]
Did you tried use `scratch`? I run without success, the binary needs `libsodium-dev` to run.

**Comment by brunowego** [comment]
I'm missing something. I will research about that. I'm get a error:

```sh
standard_init_linux.go:207: exec user process caused "no such file or directory"
```

```Dockerfile
# ...

FROM scratch

COPY --from=build /usr/local/bin/minisign /minisign

ENTRYPOINT ["/minisign"]
```

**Comment by jedisct1** [comment]
In order to not have dependencies, the binary needs to be statically linked.

With the current code, `cmake .. BUILD_STATIC_EXECUTABLES=1` may create a `Makefile` that does just that.

But I don't know `cmake` very well, so if it doesn't work, just compile everything without it:

```sh
gcc -static -Os -s -o minisign src/*.c -lsodium
``

And you'll get a standalone executable.

**Comment by wamserma** [comment]
It's already there ;)
```
docker run -it --rm nixery.dev/shell/minisign minisign -h
```
