### ISSUE TITLE
Feature request: Allow use of ssh-ed25519 keys

### ISSUE THREAD

**Issue by danielewood** [jedisct1/minisign#57]
Since people are likely to already be managing their ssh-ed25519 keys, and many will be also publishing them to GitHub as well, it would be a really nice feature to be able to use these for signatures. Perhaps also include a feature to convert the ssh pubkey format to the signify pubkey format.

This follows the [same concept](https://blog.filippo.io/using-ed25519-keys-for-encryption/) as @FiloSottile is using for his age encryption project.

**Comment by jedisct1** [comment]
Hi Daniel,

As the name suggests, Minisign's main reason to be is that it is minimal.

As a result, the specification and requirements fits in a couple lines, writing an implementation is fairly easy, and existing implementations are simple and small. And it would be a good idea to keep it that way.

Ed25519 SSH keys can be converted to Minisign keys and the other way round, but it would be better implemented as a standalone tool. Having this in signing tools and libraries would literally double their size for a feature that is not always needed.

If you feel like writing such a tool, please do :) Decrypting and reencrypting secret keys is the most complicated part; it overall should be fairly easy to do.

**Comment by cole-h** [comment]
I'm very much a layperson when it comes to cryptography, but I was wondering how one would go about converting an Ed25519 SSH key to a Minisign key ("and the other way round"). Even a high-level overview of what would need to be done would be much appreciated. I'd love to give it a shot in my free time, but I wouldn't even know where to begin.

**Comment by luizberti** [comment]
For those who stumble into this in the future, this is now supported in the Zig reimplementation of `minisign`:

https://github.com/jedisct1/zig-minisign#ssh-encoded-public-keys
