### ISSUE TITLE
Which cipher is used to encrypt the generated private key?

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/minisign#58]

**Comment by johnalanwoods** [comment]
Seems like salsa20?

**Comment by jedisct1** [comment]
Hi!

The secret key format is documented here: [minisign secret key format](https://jedisct1.github.io/minisign/#secret-key-format).

The KDF (scrypt) is used as a stream cipher.

**Comment by johnalanwoods** [comment]
Thank you sir!
