### ISSUE TITLE
Can't verify Signify signatures

### ISSUE THREAD

**Issue by Macil** [jedisct1/minisign#59]
Minisign gives me an error when I try to use it to verify a signature made by Signify. From the docs it seems like this is intended to work.

```
$ echo VGhpcyBpcyBhIHRlc3QgbWVzc2FnZS4K | base64 --decode > message.txt
$ signify -G -p sign.pub -s sign.sec
passphrase: (z)
confirm passphrase: (z)
$ cat sign.sec
untrusted comment: signify secret key
RWRCSwAAACrVwvFk3aEyZFmPQ3kkX8eVAXYt/DvCvS3JD4o2QgWw5dPT1GwM0/u9lgqB03XQqr5yJJx9f49kmX5vd6NBBHa0rk4e9XC8mVs6Q1jWMCmO6aQTjcLOHFhLr9Vxc+W+NSw=
$ signify -S -s sign.sec -m message.txt
passphrase: (z)
$ cat message.txt.sig
untrusted comment: verify with sign.pub
RWTJD4o2QgWw5Yl4xS5JBgxC4Zv+KnDXYfDJzpE6LU/FZbs5vHq2kVJ5E7ruNvUUL+sg1/OSOvnI6N6A57wpc2VrWwujA/m8mwU=
$ ls
message.txt     message.txt.sig sign.pub        sign.sec
$ signify -V -p sign.pub -m message.txt -x message.txt.sig
Signature Verified
$ minisign -V -p sign.pub -m message.txt -x message.txt.sig
message.txt.sig: Undefined error: 0
$ minisign -v
minisign 0.8
```

The other way around works okay. Signify can verify minisign signatures:

```
$ rm sign.pub sign.sec
$ minisign -G -p sign.pub -s sign.sec
Please enter a password to protect the secret key.

Password: (z)
Password (one more time):
Deriving a key from the password in order to encrypt the secret key... done

The secret key was saved as sign.sec - Keep it secret!
The public key was saved as sign.pub - That one can be public.

Files signed using this key pair can be verified with the following command:

minisign -Vm <file> -P RWSaFhePk+tC9vTTi+yeIO4Wl6ncKXi9+ic+Rj0nohuwNC/ZWZLgBoEx
$ cat sign.sec
untrusted comment: minisign encrypted secret key
RWRTY0Iy8Ih0p+rQl2n6xucscPJOdSK48PM+Un6uFrhB74CZR/oAAAACAAAAAAAAAEAAAAAAXEf+5XzHb5GZ0vHG9ToGyICcgqEyB6kj1FAX0o/rO5o6bjIPvf3dJYo9qbOUYhWCv+56u9rnEywSGLzL9+XFmp3B2wwh14cw2+VsVe6saQG/fjrI2/C3vjUbpX1pKzGhGO391w6IawQ=
$ minisign -S -s sign.sec -m message.txt
Password: (z)
Deriving a key from the password and decrypting the secret key... done
$ cat message.txt.minisig
untrusted comment: signature from minisign secret key
RWSaFhePk+tC9snG7mzd/58ED3RdUFmO3KkyR5K8Vx/4WJCkRqHKBtUAVe4zSkoG2TgDGAImnjKBmHChbbjAxoD+TaY81Owx6AE=
trusted comment: timestamp:1563858228	file:message.txt
D1HGUOIL0Qc9OqibpK7QwMO3crzhoUdaur25n1eyMBL2q4r0loThMZycevcN1bMOg61h6cA5+PuBY8kE6MxFAw==
$ minisign -V -p sign.pub -m message.txt -x message.txt.minisig
Signature and comment signature verified
Trusted comment: timestamp:1563858228	file:message.txt
$ signify -V -p sign.pub -m message.txt -x message.txt.minisig
Signature Verified
```

Just in case this is somehow system-specific, I'm on MacOS with minisign and signify installed from Homebrew.

```
$ brew info signify-osx
signify-osx: stable 1.4 (bottled), HEAD
Cryptographically sign and verify files
https://man.openbsd.org/signify.1
/usr/local/Cellar/signify-osx/1.4 (6 files, 174.8KB) *
  Poured from bottle on 2019-07-22 at 14:46:59
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/signify-osx.rb
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 28 (30 days), 59 (90 days), 221 (365 days)
install_on_request: 28 (30 days), 58 (90 days), 208 (365 days)
build_error: 0 (30 days)
$ brew info minisign
minisign: stable 0.8 (bottled)
Sign files & verify signatures. Works with signify in OpenBSD
https://jedisct1.github.io/minisign/
/usr/local/Cellar/minisign/0.8 (6 files, 38.1KB) *
  Poured from bottle on 2019-07-22 at 13:40:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/minisign.rb
==> Dependencies
Build: cmake ✔
Required: libsodium ✔
==> Analytics
install: 85 (30 days), 172 (90 days), 644 (365 days)
install_on_request: 63 (30 days), 116 (90 days), 420 (365 days)
build_error: 0 (30 days)
```

**Comment by jedisct1** [comment]
I don't think it works that way, because minisign expects the trusted comment section to be present.

**Comment by jedisct1** [comment]
The error message was indeed not very clear.

This has been improved. Thanks for the heads up :)

**Comment by johankool** [comment]
I ran into this issue today. I was surprised to still see it despite the fix being mentioned here, but it seems it has been a while since the last release. I'm on 0.8 which was released in 2018.

**Comment by fkooman** [comment]
The strange thing is that on Linux it works for me, it doesn't give this error...

You can on macOS also install `signify-osx` from Homebrew to verify signify signatures.

**Comment by jneplokh** [comment]
> The strange thing is that on Linux it works for me, it doesn't give this error...

Same for me. On MacOS, I get the error about "Trusted comment not present," but on Linux minisign can verify Signify signatures just fine.

**Comment by jedisct1** [comment]
`minisign` creates signatures that can be verified by `signify`.

But `signify` signatures cannot be verified with `minisign`. Trusted comments are important to describe what has been signed in addition to the fact that something has been signed.

**Comment by jneplokh** [comment]
Oh ok, so the compatibility is one-way, as `minisign` relies on the trusted comments, correct?

**Comment by jedisct1** [comment]
Yes.

**Comment by crd477** [comment]
> `minisign` creates signatures that can be verified by `signify`.
> 
> But `signify` signatures cannot be verified with `minisign`. Trusted comments are important to describe what has been signed in addition to the fact that something has been signed.

For what it's worth, I just wasted maybe 20 minutes yesterday morning independently reaching this same conclusion.  I think it would be a big help if you could incorporate it into the documentation page, maybe in a section like "Compatibility Notes" or "Interoperability Notes".

**Comment by FranklinYu** [comment]
Signal boost for the last comment. I found via trial-and-error that `minisign -S -l` (note the `-l` switch for “legacy” mode) creates signature that can be verified by `signify -V`. The [OpenBSD package description](https://openbsd.app/?search=minisign) also mentioned the compatibility without enough details.

**Comment by FranklinYu** [comment]
How do we propose change to the GitHub Pages? Do we simply create PR to the `gh-pages` branch, or is it generated from some source-of-truth?

Some of it seems to be the same as https://github.com/jedisct1/minisign/blob/master/src/manpage.md but there are other sections (like https://jedisct1.github.io/minisign/#trusted-comments) not found in the master branch.

**Comment by jedisct1** [comment]
Yes, the GitHub pages are in the `gh-pages` branch and you're welcome to send PRs against that branch!

Everything is in the `index.html` and `stylesheets` files. Other files doesn't exist in that branch.
