### ISSUE TITLE
minisign-py has no code

### ISSUE THREAD

**Issue by seanlynch** [jedisct1/minisign#60]
There's no actual code in the project's repo, and there's an issue that's been open for a while on the project asking for the status and pointing out that there's no code there. I think it's never actually had a release. Probably shouldn't list it as an implementation.

**Comment by jedisct1** [comment]
Removed, thank you!

**Comment by x13a** [comment]
Ported to python.

[py-minisign](https://github.com/x13a/py-minisign)

**Comment by jedisct1** [comment]
This is awesome! Good job @x13a!
