### ISSUE TITLE
no signature for 0.8 source release

### ISSUE THREAD

**Issue by fkooman** [jedisct1/minisign#61]
There is no `.minisig` for the 0.8 source code release tar. Could you add one?

(This as part of the ongoing work of using Minisign in Fedora, see https://lists.fedoraproject.org/archives/list/packaging@lists.fedoraproject.org/thread/WNR34OH3KVPKMGY4Z62CUPREEOVJJJNH/)

**Comment by jedisct1** [comment]
Done!

**Comment by fkooman** [comment]
Can you do the same for the 0.9 release? Thanks!

**Comment by jedisct1** [comment]
Source code tarball added, thanks!

**Comment by jedisct1** [comment]
Added.

**Comment by fkooman** [comment]
And for the 0.11 release? ;-)

**Comment by jedisct1** [comment]
Source code tarball added, thanks!
