### ISSUE TITLE
Aborted (core dumped) when crypto_pwhash_scryptsalsa208sha256() returns -1

### ISSUE THREAD

**Issue by pysiak** [jedisct1/minisign#62]
```
$ ./minisign -G
Please enter a password to protect the secret key.

Password:
Password (one more time):
Deriving a key from the password in order to encrypt the secret key... Aborted (core dumped)
```
It's this part of generate():
```
    if (crypto_pwhash_scryptsalsa208sha256
        (stream, sizeof seckey_struct->keynum_sk, pwd, strlen(pwd),
         seckey_struct->kdf_salt,
         le64_load(seckey_struct->kdf_opslimit_le),
         le64_load(seckey_struct->kdf_memlimit_le)) != 0) {
        abort();
    }
```

Any guidance on what could be going on here?
I'm using libsodium-1.0.18 built without configure parameters on ubuntu 18.04.3 LTS (gcc-7.4.0)

**Comment by jedisct1** [comment]
Hi!

It means that not enough memory is available.

Since signing is not a frequent operation, the parameters of the key stretching function are intentionally higher than usual.

They are set here:

```
    le64_store(seckey_struct->kdf_opslimit_le,
               crypto_pwhash_scryptsalsa208sha256_OPSLIMIT_SENSITIVE);
    le64_store(seckey_struct->kdf_memlimit_le,
               crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE);
```

And you can freely change them, either to `_INTERACTIVE` or whatever values suit best your platform. This has no effect on signature verification.

**Comment by pysiak** [comment]
Right, thanks for the hint!
minisign worked for me before but now I was on a 0.5G RAM box with no swap.
When I added a 0.5G swap it still aborted, I added more and I seem to have it working but memory consumption is high. I know it's an low-provision box but is 600MB+ normal?

```
$ smem
  PID User     Command                         Swap      USS      PSS      RSS
17891 solt     -su                              960     1404     1577     2380
19157 solt     /usr/bin/python /usr/bin/sm        0     8140     8402     9376
19151 solt     minisign -G                   686396   362464   362491   362664
```

**Comment by jedisct1** [comment]
With the default parameters, the function that derives a key from a password requires 1 GB RAM.

This makes brute-force attacks significantly more expensive. But once again the default parameters are a bit extreme, and assume that files are signed on a laptop.

It's totally fine to change these parameters for your needs.
