### ISSUE TITLE
empty strip command in default on porting to openwrt

### ISSUE THREAD

**Issue by peter-tank** [jedisct1/minisign#66]
https://github.com/jedisct1/minisign/blob/21a6f41c0648dc1337dcaeffc45a3ce65728e7fe/CMakeLists.txt#L83-L86

openwrt/include/cmake.mk
https://github.com/openwrt/openwrt/blob/366e6ef5c342f5926d9ab07166b8a40734393dc2/include/cmake.mk#L62-L69

porting
https://github.com/peter-tank/openwrt-minisign/blob/e9de790aad17cf85a7d04d749a4240a3be120c96/Makefile#L77

**Comment by jedisct1** [comment]
Hi,

Can you clarify what this issue is about?

**Comment by peter-tank** [comment]
`CMAKE_STRIP` may empty, check defined is not enough for openwrt cmake toolchain.

**Comment by jedisct1** [comment]
I don't know how to use `cmake`. Can you send a pull request that fixes the issue?
