### ISSUE TITLE
Error while loading shared libraries: libsodium.so.23

### ISSUE THREAD

**Issue by arnauldb** [jedisct1/minisign#67]
Hello,

on Linux Mint 18.3 with minisign successfully compiled & installed (I installed libsodium-1.0.18), I obtain this error while tryng to use minisign:

> minisign: error while loading shared libraries: libsodium.so.23: cannot open shared object file: No such file or directory

Thank you.

**Comment by jedisct1** [comment]
Hi,

How did you install libsodium?

If manually compile a library on Linux, you need to type `ldconfig` in order for the system to find it.

**Comment by arnauldb** [comment]
Hi, 

I updated the cache with `sudo ldconfig` as you said and it is working fine now. 

Thank you.
