### ISSUE TITLE
Different exit status for errors other than validation failure?

### ISSUE THREAD

**Issue by AnvilStriker** [jedisct1/minisign#7]
It would be handy (when invoking `minisign -V` from a script, for example) if a different exit status were used to distinguish between "real" verification failures and other errors (argument error, nonexistent or unreadable file, base64 conversion failure, etc.). 

For example, exit status 0 means verification succeeded (as it does today), 1 means verification failed (strictly), 2 means some other problem occurred.

See the `cmp` utility (on Ubuntu and OS X, at least) for an example of a program that distinguishes errors this way.

Thank you.

**Comment by jedisct1** [comment]
This is an excellent suggestion.

Done in 9546c80674ed780e62066c49b141b4ad63e5ca45

**Comment by AnvilStriker** [comment]
Thank you very much!

**Comment by jedisct1** [comment]
Thanks for suggesting this! I'm gonna tag a new release soon.
