### ISSUE TITLE
Keys generated from OS X static build unusable with other builds

### ISSUE THREAD

**Issue by r1b** [jedisct1/minisign#71]
I generated keys with the 0.8 OS X static build found in `minisign-osx.zip` on the releases page. If I build from source on any other platform (I have tried OS X and Linux, both static and dynamic builds) I cannot use these keys to sign and verify files. The verification always fails.

I have attached a zip with:

* minisign-osx: the static build from the releases page
* minisign: a static build I created with the latest libsodium in homebrew
* minisign.pub / minisign.key: keys generated from minisign-osx

[minisign-osx-repro.zip](https://github.com/jedisct1/minisign/files/4325721/minisign-osx-repro.zip)

**Comment by r1b** [comment]
Note that the private key has an empty password

**Comment by r1b** [comment]
I tried this with a key that has a password and I get the same result

**Comment by jedisct1** [comment]
Weird.

The code was recompiled and the `minisign-osx.zip` was reuploaded. Can you give it a try?

**Comment by r1b** [comment]
When invoking that `minisign` I get:

```dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/minisign (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ____chkstk_darwin
  Referenced from: /usr/local/bin/minisign (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib

Abort trap: 6```

I'm on OS X 10.13.6 btw.

Thanks for your help!

**Comment by jedisct1** [comment]
Ooh, MacOS 10.13 is very old.

I uploaded new binaries that may be compatible with it, but I have no ways to test that it works on old versions of MacOS.

**Comment by r1b** [comment]
Okay, the latest build works on my machine. It works in the sense that if I generate keys with this build and use any other minisign build I can sign / verify files as expected.

I still have a problem though, which is that I generated keys for my application with the *old* build and now those keys are unusable with any other OS X build, including the one you just uploaded.

Basically what I'm trying to say is that there is something wrong with the *keys* that were generated from that build. For example, if you use this latest OS X build to sign and verify a file with the keys I provided in the zip [1] (which were generated from the old build) you should always be able to sign a file but also always be unable to verify that signature.

It's looking like I'm going to need to rotate the keys I'm using in my application but I want to be absolutely sure that I'm not crazy and that in fact those keys are busted somehow.

[1] For the gentle reader, these were freshly generated testing keys - NOT in use by any application.

**Comment by taion** [comment]
BTW, looks like this was because the original static build was linked against libsodium 1.0.16, which stored keys in a different format when `ED25519_NONDETERMINISTIC` was defined.

The key format was changed in 1.0.17 onward per https://github.com/jedisct1/libsodium/compare/1.0.16...1.0.17#diff-9f8d35b5046ff922edb045b081249af6, but it means that keys generated in 1.0.16 with this setting cannot be used in 1.0.17 onward.

**Comment by taion** [comment]
Oops, here are the correct reference links:
- https://github.com/jedisct1/libsodium/commit/d3976446a0c19aa9fe6f66523741126869a4990e#diff-9f8d35b5046ff922edb045b081249af6
- https://github.com/jedisct1/libsodium/commit/055e0ae82c8a478ab3eb8f5608c34dc718304275#diff-d8d30bcb8f4366a400da1a125a48cb17

@jedisct1 I don't have ready access to a Windows box right now to check, but you might want to double-check that the pre-built win32 binary for 0.8 isn't built that way.

**Comment by r1b** [comment]
<img width="674" alt="Screen Shot 2020-03-26 at 2 47 31 PM" src="https://user-images.githubusercontent.com/5550520/77684748-c4fa9c00-6f70-11ea-91ac-fe7c13fae73c.png">

I checked, it isn't. So this issue only affects that particular build.

**Comment by deni** [comment]
@r1b What was your conclusion? Was the problem due to the new format?

**Comment by r1b** [comment]
@deni yes, we were able to continue using the original generated keys by linking minisign with libsodium 1.0.16 configured with `CFLAGS="-DED25519_NONDETERMINISTIC=1"`
