### ISSUE TITLE
Not an issue but a question: how to use this tool?

### ISSUE THREAD

**Issue by OnionSalt** [jedisct1/minisign#72]
I'll use dnscrypt-proxy as example here:
https://github.com/DNSCrypt/dnscrypt-proxy/releases

There are 2 files:
```
dnscrypt-proxy-win64-2.0.39.zip
dnscrypt-proxy-win64-2.0.39.zip.minisig
```

So, how to verify dnscrypt-proxy-win64-2.0.39.zip?
I tried:
```
minisign -Vm dnscrypt-proxy-win64-2.0.39.zip -x dnscrypt-proxy-win64-2.0.39.zip.minisig
```
It returns:
```
minisign.pub: No such file or directory
```
Am I missing something?

Also, the content of dnscrypt-proxy-win64-2.0.39.zip.minisig:
```
untrusted comment: signature from minisign secret key
RWTk1xXqcTODebOGu6R+Ra/vkbM49RQmVrcFEeJGsjaH3wtC0yOlEDuggYzE/FnDEkWrOzVmbi08G8j58l4OFNCiSMPQq9N8JQg=
trusted comment: timestamp:1580467116	file:dnscrypt-proxy-win64-2.0.39.zip
KT/KXkctmtxEpNlC1r79Li/y6Fop77Bv5Pz1+0MdDEYY7FGwNuKyF9Cbyck9IPru7tOIyn2ovDwXBqdCziPrAw==
```
I'm confused, the .minisig file is in plain text and the secret key is in the file?
I don't know, shouldn't secret key supposed to be . . . . secret?

**Comment by jedisct1** [comment]
This is explained in the [first page of the dnscrypt-proxy documentation](https://github.com/DNSCrypt/dnscrypt-proxy/wiki/Installation#verification-of-downloaded-files)
