### ISSUE TITLE
allow to change location of private keys

### ISSUE THREAD

**Issue by sebhoss** [jedisct1/minisign#73]
Right now private keys end up in `~/.minisig/`, however I would prefer to use something like `XDG_DATA_HOME` instead and get rid of the dot-folder in my home directory. Typically this is done with an environment variable (like `MINISIG_KEY_DIR`) which can be set by any user to whatever value they want.

**Comment by jedisct1** [comment]
It's called `MINISIGN_CONFIG_DIR`.

**Comment by jedisct1** [comment]
(see the man page)

**Comment by toastal** [comment]
Shouldn't `XDG_DATA_HOME/minisign` be the default value for `MINISIGN_CONFIG_DIR` though?
