### ISSUE TITLE
Change password protecting secret key

### ISSUE THREAD

**Issue by johnalanwoods** [jedisct1/minisign#75]
As the secret key is encrypted with a key derived from a password, can this be changed retrospectively to a new password?

If not, can the secret key scalar value be exfiltrated and used to generate the same pub/priv pair with a new password?

**Comment by jedisct1** [comment]
Hi!

Yes, absolutely, the secret material could totally be reencrypted with a different key.

This is not implemented in this command-line tool yet, but this is not a design limitation.

**Comment by johnalanwoods** [comment]
Thanks Frank!

I’ll take a look at implementing this.

**Comment by johnalanwoods** [comment]
I have this working now by inject the seckey_struct into the generate function.

It's a hack but it works.

@jedisct1 would you see value in me submitting a PR for this feature if I cleaned up the code?
