### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by JohnPlanetary** [jedisct1/minisign#77]
It would be nice for minisign to be fully supported in the biggest mobile platform "Android OS" including fully functionally GUI for anyone be able to use it also there.

Support on iOS would probably also be nice, but since developer account is needed and I think is not something trivial, at least being available for Android would be a nice improvement.

**Comment by jedisct1** [comment]
Hi,

Unfortunately, I don’t know anything about Android, and I can’t even picture what such an application would do.

You apparently do, so you’re in a far better position to work on this!
