### ISSUE TITLE
Ubuntu PPA is not up-to-date

### ISSUE THREAD

**Issue by lucidBrot** [jedisct1/minisign#79]
The latest release on github is 0.9 but apt installs version 0.8.
Is it generally still maintained, or would it be better to not rely on it?

### Reproduce
```bash
$ sudo add-apt-repository ppa:dysfunctionalprogramming/minisign
$ sudo apt-get update
$ sudo apt-get install minisign
$ minisign -version
minisign 0.8
``` 

### System Information
```bash
$ uname -a
Linux motorbrot 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jedisct1** [comment]
I have no idea...

This package is maintained independently; I don't use Linux.

The best thing to do would be to contact the author of this package.

**Comment by lucidBrot** [comment]
I have sent them an email. Will update here once I hear back.

**Comment by jedisct1** [comment]
Thank you!

**Comment by lucidBrot** [comment]
> I completely missed the new release back in June. I can update the PPA later today.
> I *was* planning to keep on top of it regularly but things have been a bit hectic recently.

The version 0.9 is now available in the PPA and it sounds like future versions will be too.
