### ISSUE TITLE
-G overwrites keys without warning

### ISSUE THREAD

**Issue by Safari77** [jedisct1/minisign#8]
Maybe ask if user wants to overwrite?

**Comment by jedisct1** [comment]
Indeed, that would be a nice addition. Thanks for suggesting this!

**Comment by JayBrown** [comment]
Alternative proposal: just do it the usual OS X (macOS) way and add a 1, 2, 3, 4 before .pub and .key, if key pairs with the new or default name already exist in one of the target directories, and don't overwrite the existing keys at all with the standard `-G` option. Instead, include an `-R` option to minisign, which, if used, will ensure that existing key pairs with the same name as the new pair will be overwritten/replaced, even if only one of the keys (.pub or .key) has the same name.

**Comment by jedisct1** [comment]
Thanks for your feedback!

Version 0.7 is out, and `-G` doesn't overwrite the keys any more.

An additional switch (`-f`) is now required in order to force this operation.
