### ISSUE TITLE
Docker version is outdated

### ISSUE THREAD

**Issue by HacKanCuBa** [jedisct1/minisign#82]
Latest versions seems to be 0.9 yet the version from the Docker container yields 0.8:

```
:~$ sudo docker pull jedisct1/minisign
Using default tag: latest
latest: Pulling from jedisct1/minisign
277dae63672e: Pull complete 
Digest: sha256:63b5e64f00811f580ae192f5087277a27b4f0eec157202dcc278945e392cbf99
Status: Downloaded newer image for jedisct1/minisign:latest
docker.io/jedisct1/minisign:latest

:~$ sudo docker run --rm -i jedisct1/minisign -v
minisign 0.8
```

However it seems to have characteristics from the 0.9 version such as the `-R` parameter and according to the release description, its very existence. So it's probably that the version number was wrong when the image was built.

**Comment by jedisct1** [comment]
The image has been rebuilt and reuploaded.

Thanks!
