### ISSUE TITLE
libhydrogen implementation

### ISSUE THREAD

**Issue by aparcar** [jedisct1/minisign#85]
Hi, is there a version `minisign` that uses `libhydrogen` rather than the more complex `libsodium`? Or is anyone aware of anyone working on such?

**Comment by jedisct1** [comment]
There isn't, but it would be incompatible, since libhydrogen has different algorithms for signing and password stretching.

There are reimplementations in Rust and in PHP, though.

**Comment by naturallymitchell** [comment]
> There are reimplementations in Rust and in PHP, though.

https://github.com/jedisct1/rust-minisign

https://github.com/jedisct1/rust-minisign-verify

**Comment by jedisct1** [comment]
@naturallymitchell There are a little bit more since 2020: https://github.com/jedisct1/minisign#additional-tools-libraries-and-implementations

**Comment by naturallymitchell** [comment]
@jedisct1 what do you think about https://github.com/sodiumoxide/sodiumoxide please?
