### ISSUE TITLE
Support multiple public key arguments

### ISSUE THREAD

**Issue by deni** [jedisct1/minisign#87]
Running:
```
minisign -Vm file \
    -P RWSyG2KhGWkcHWrdoRBGuTU1RtilvRe2ux5AM3Fk1yUrSmdjB3UCGq96 \
    -P RWSpCMDA8waLAyztJRy29AxQvqQyXI6W8q9kgpMLRHN5A95yX3E8ErOe
```

seems to only check against the last key, whereas I would expect it to either 1) throw an error or 2) check against all specified keys.

**Comment by sergeevabc** [comment]
This tool is too complicated to use on daily basis.
I had to read manual a few times before figuring out the right command to verify just one file was
`minisign -V -x minisign-win64.zip.minisig -P RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3 -m minisign-win64.zip`

**Comment by jedisct1** [comment]
@sergeevabc I must have missed your PR improving the documentation :)

**Comment by madblobfish** [comment]
Hi @jedisct1
Thanks a lot for the tool! I do not find it complicated to use, but I also missed this Feature. I think throwing an error is the least to do. It surprised me that the second public key was silently ignored.
Would you accept a PR for throwing an error in that case? Or alternatively I could also try to implement the loop over all keys to validate.

**Comment by deni** [comment]
@sergeevabc's comment was off-topic, so I do not understand on what basis this issue was closed. I am confused whether you acknowledge this bug, @jedisct1.

**Comment by sergeevabc** [comment]
> @sergeevabc I must have missed your PR improving the documentation :)

@jedisct1, it reminds of this [picture](https://bafybeieej6nkkewxow34lwe6fdwad2bkuzoauynoftk5tvg25ity4rcv7y.ipfs.w3s.link/problemsolved.webp).

The bottom line is that Minisign got so many parameters that it turned into a GPG-like monster. From afar it is admirable, but it is scary to approach. It was for this reason, a lack of simplicity, that [Signify](https://www.openbsd.org/papers/bsdcan-signify.html) was once developed. And I doubt we can fix that just by editing the documentation. First, it would be worth simplifying the utility screen itself by separating the main actions from the secondary ones and providing examples right there. Once you've successfully completed one or two actions, it's easier to go deeper, or to return in a while, knowing that you won't get lost. See how this is done in [Age](https://basedbin.fly.dev/p/VJ3u39.txt).
