### ISSUE TITLE
RAM usage/duration on key generation and signing

### ISSUE THREAD

**Issue by AladW** [jedisct1/minisign#88]
When using a longer passphrase (e.g. 25 characters), `minisign -G` takes ~740mb RES on my machine and several minutes to complete. `signify -G` on the other hand is instant and takes ~1.7mb. 

I'm not sure on the cause - the only difference I could see is deterministic signatures which I guess signify doesn't use. Signing files takes a similar amount of resources.

Compare (times include passphrase input):
```
$ /usr/bin/time -f "mem=%K RSS=%M elapsed=%E cpu.sys=%S .user=%U" signify -G -p test.pub -s test.sec
passphrase: 
confirm passphrase: 
mem=0 RSS=1676 elapsed=0:05.21 cpu.sys=0.00 .user=0.44

$ /usr/bin/time -f "mem=%K RSS=%M elapsed=%E cpu.sys=%S .user=%U" minisign -G -p test2.pub -s test2.sec
Please enter a password to protect the secret key.

Password: 
Password (one more time): 
Deriving a key from the password in order to encrypt the secret key... done

The secret key was saved as test2.sec - Keep it secret!
The public key was saved as test2.pub - That one can be public.

Files signed using this key pair can be verified with the following command:

minisign -Vm <file> -P RWQWyblp10+UPC6vtFkrbpQ34cGUStt21cPfcoDXaWyY5o0arBuOz6DB

mem=0 RSS=828328 elapsed=2:50.81 cpu.sys=11.80 .user=3.14
```

System: Arch Linux
Version: minisign 0.9

**Comment by jedisct1** [comment]
This is expected.

The password is stretched using the Scrypt function, that intentionally requires a large amount of memory and CPU in order to slow down brute force attacks.

**Comment by AladW** [comment]
Thanks. Since I don't need to slow down brute force attacks by such an amount for my purposes (and setting the amount of memory or operations doesn't seem documented), I set:
```
#define crypto_pwhash_scryptsalsa208sha256_MEMLIMIT_SENSITIVE 1073741824U
```
to a lower value `134217728U` (128M) in `src/libsodium/include/sodium/crypto_pwhash_scryptsalsa208sha256.h`. That made key generation complete in a few seconds.
