### ISSUE TITLE
False positive on virustotal for windows bin/zip (hopefully :))

### ISSUE THREAD

**Issue by c33s** [jedisct1/minisign#90]
### exe file

- SecureAge APEX: Malicious
- VBA32: BScope.Trojan.Staser

https://www.virustotal.com/gui/file/6b31e8016dbd8c41c0aa94984761cace7562b78663b8413f25cc2c34d04080a5/detection

### zip file

- VBA32: BScope.Trojan.Staser

https://www.virustotal.com/gui/file/2068aab3d211584cee078df0c9dd178cdaaed1433af3bf8cef51fa5a39eef7d0/detection

**Comment by jedisct1** [comment]
False positives should be reported to these AV's vendors. I don't work for them, there's not much I can do :)

**Comment by c33s** [comment]
thought you maybe want to change something in the code or report it so your nice tool is "clean" for everyone

**Comment by jedisct1** [comment]
It is likely that these tools choke because they the code contains some crypto. I'm not going to remove cryptography from minisign, nor spend time reporting bugs on tools I don't use, on a platform I don't have. You're in a far better position for that :)
