### ISSUE TITLE
[Suggestion] argument checking should be done before key handling

### ISSUE THREAD

**Issue by c33s** [jedisct1/minisign#91]
>` Deriving a key from the password and decrypting the secret key... done`

is quite time consuming and also the password has to be entered first.

```
minisign -Sm nonexistingfile.txt
Password:
Deriving a key from the password and decrypting the secret key... done

nonexistingfile.txt: No such file or directory
```

would give a better UX if first all file checks are done and after that the crypto handling so we have an early exit on missing files.

so in the upper case we have no password prompt at all
```
minisign -Sm nonexistingfile.txt
nonexistingfile.txt: No such file or directory
```

**Comment by jedisct1** [comment]
Signing files requires the key, so checking the files presence would increase the code complexity for a quite uncommon scenario.
