### ISSUE TITLE
wildcard *. does not work (on windows?)

### ISSUE THREAD

**Issue by c33s** [jedisct1/minisign#92]
```
ls *.yaml
config.yaml  hiera.yaml  hiera-eyaml-vagrant.yaml  r10k.yaml  Vagrantconfig.yaml

minisign -Sm *.yaml
Password:
Deriving a key from the password and decrypting the secret key... done

*.yaml: Invalid argument
```

also tested this in bash on windows, there it works.

**Comment by jedisct1** [comment]
Maybe powershell doesn't do wildcard expansion or requires a different syntax?

I don't know much about powershell, sorry :(

**Comment by 43v6c3463** [comment]
Windows doesn't do wildcard expansion and instead expects the application to handle it (applies to both powershell and cmd). Fixing this should be fairly simple: https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-crt/crt/wildcard.c

**Comment by jedisct1** [comment]
@43v6c3463 does adding `int _dowildcard = -1` actually changes the behavior?

Looks like this is something that can be configured in MingW, not in applications using its library.

Can you check?
