### ISSUE TITLE
Encryption/decrypytion support?

### ISSUE THREAD

**Issue by teran-mckinney** [jedisct1/minisign#93]
Maybe this is beyond the scope of minisign, but it seems like since you have public keys and private keys, it would be possible to encrypt documents to the public key much as you would with PGP.

I could see that being pretty useful. Some way to send encrypted messages to minisign key users using their public key.

I know they could just use PGP, but at first thought I think it wouldn't be terribly excessive to do it inside minisign.

**Comment by jedisct1** [comment]
Yes, this is a bit out of scope.

For encryption to public keys, you may want to take a look at [age](https://github.com/FiloSottile/age).

**Comment by teran-mckinney** [comment]
Gotcha, thank you!
