### ISSUE TITLE
Can I store the private key in softhsm

### ISSUE THREAD

**Issue by stanimirivanovde** [jedisct1/minisign#94]
We are looking to sign our final tar.gz artifact upon release. Currently we’ve prototyped OpenSSL and softhsm as a solution. Could we use minisign instead to manage the signatures but still store the keys in softhsm? This will help us when we transition to having a real HSM.

**Comment by jedisct1** [comment]
Hi,

I've no experience with softhsm. But you apparently do, so you're probably better suited to answer that question 😀
