### ISSUE TITLE
add support for security sticks, e.g. Yubikey 

### ISSUE THREAD

**Issue by orolhawion** [jedisct1/minisign#95]
I tried to put the signing key onto my Yubikey 5c using PIV slot 9c:

```
$ ykman piv keys import 9c ~/.minisign/minisign.key
Enter a management key [blank to use default key]: 
Enter password to decrypt key: 
Wrong password.
Enter password to decrypt key: 
Aborted!
```

The correct password is not accepted. Perhaps this is an issue of ykman, but I just wanted to let you know too.

**Comment by jedisct1** [comment]
The `ykman` tool is very unlikely to encrypt and decrypt keys the same way as minisign.

**Comment by jstasiak** [comment]
> FYI, we have a proposal from the community to implement hardware key-backed `minisign` signatures via a custom CTAP2 command (FIDO extension) for the Solo 1 device.

Hey, is there a link to the proposal or any information about its current state?

**Comment by nickray** [comment]
Talking about https://github.com/solokeys/solo1-cli/pull/137, but it's not currently active. Also starting to get off-topic for this repo :)
