### ISSUE TITLE
can i use my ssh-ed25519 key to sign or verify?

### ISSUE THREAD

**Issue by arxim-lab** [jedisct1/minisign#97]
they are both based on ed25519. can we combine them in a single keyfile, just like age? ssh-ed25519 key is easier to get than minisign native key.

**Comment by jedisct1** [comment]
I didn't see anything about that in the documentation.

However, Minizign can encode minisign keys to the SSH format, and load them: https://github.com/jedisct1/zig-minisign

I would still highly recommend using one key for one application.

**Comment by pinpox** [comment]
@jedisct1 You closed this as completed, but I'm not finding how to do it. Is this supported now?
I would like to use one SSH key for everything
