### ISSUE TITLE
#75 is still open technically

### ISSUE THREAD

**Issue by artemislena** [jedisct1/minisign#99]
https://github.com/jedisct1/minisign/issues/75 ‒ I actually have (or at least had; it forced me to change my key once) the same issue… OP in there, after closing the issue, asked if he should submit a PR, however, no response came (presumably because there are no notifications on comments on closed issues?)… So this issue's just a reminder, and a possible continuation of the original one, I guess…

**Comment by FantasyCookie17** [comment]
I suppose it would be a good idea to ping @johnalanwoods on this.

**Comment by infa-jowoods** [comment]
Hey @FantasyCookie17  - yep I got it working, it's a really ugly implementation but it works and cleanly resaves the private key with a new password, and from there you just go back to using the regular client. LMK if you want it

**Comment by FantasyCookie17** [comment]
Well… I'd love to have it implemented in Minisign, however, I'd rather be able to have the benefits from being able to install it from my package manager and such, meaning I'd rather not use custom patches… So what would be great is if you could make the code quality good enough to have it merged in mainline Minisign. Perhaps just open a PR and we'll see? If it actually isn't good enough, perhaps someone else (e.g. @jedisct1 or even me, given I do know a bit of C) might be able to polish it.
